# Generated by Django 3.2.5 on 2021-08-08 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leads',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
